{% set name = "nettle" %}
{% set version = "3.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fe9ff51cb1f2abb5e65a6b8c10a92da0ab5ab6eaf26e7fc2b675c45f1fb519b5

build:
  number: 0
  # Nettle uses GNU autotools (configure/make) which doesn't natively support Windows MSVC toolchain.
  # It requires either MSYS2/MinGW or complex cross-compilation setup.
  skip: True  # [win]
  ignore_run_exports_from:
    # This is only needed for the test suite
    - {{ compiler('cxx') }}
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=nettle
    - {{ pin_subpackage('nettle', max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - m4
    - make
    - libtool
  host:
    # https://git.lysator.liu.se/nettle/nettle/-/blob/nettle_3.10.2_release_20250626/configure.ac?ref_type=tags#L270
    # gmp >=6.1
    - gmp {{ gmp }}

test:
  commands:
    - nettle-hash -V
    - nettle-pbkdf2 -V
    - test -f ${PREFIX}/lib/libnettle${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libhogweed${SHLIB_EXT}
    - test -f ${PREFIX}/lib/pkgconfig/nettle.pc
    - test -f ${PREFIX}/lib/pkgconfig/hogweed.pc
    - test ! -f ${PREFIX}/lib/libnettle.a
    - test ! -f ${PREFIX}/lib/libhogweed.a

about:
  home: https://www.lysator.liu.se/~nisse/nettle
  license: GPL-2.0-or-later OR LGPL-3.0-or-later
  license_family: GPL
  license_file:
    - COPYINGv2
    - COPYINGv3
    - COPYING.LESSERv3
  summary: Nettle is a low-level cryptographic library that is designed to fit easily in more or less any context
  description: |
    Nettle is a low-level cryptographic library that is designed to fit easily in more or less any context.
    In crypto toolkits for object-oriented languages (C++, Python, Pike, ...), in applications like LSH or GNUPG, or even in kernel space.
    Simple, fast, extensible JSON encoder/decoder for Python
  doc_url: https://www.lysator.liu.se/~nisse/nettle/nettle.html
  dev_url: https://git.lysator.liu.se/nettle/nettle

extra:
  recipe-maintainers:
    - sachalau
    - mingwandroid
